### ISSUE TITLE
Nutzung des fmtcount Pakets

### ISSUE THREAD

**Issue by GoogleCodeExporter** [UweZiegenhagen/spendenquittungen-mit-latex#1]
```
\documentclass[ngerman]{minimal}
\usepackage{babel}
\usepackage{fmtcount}

\begin{document}

4: \numberstringnum{4}

31: \numberstringnum{31}

123: \numberstringnum{123}

\end{document}
```

Original issue reported on code.google.com by `ziegenha...@gmail.com` on 20 Oct 2013 at 5:52

Attachments:
- [numbers.pdf](https://storage.googleapis.com/google-code-attachments/spendenquittungen-mit-latex/issue-1/comment-0/numbers.pdf)

**Comment by vv01f** [comment]
ich bekomme für \numberstringnum{31} sauber "einunddreißig" heraus, womöglich ist das gefixt
ABER: \numberstringnum{31.24} oder \numberstringnum{31,24} führen zu einem nicht abgefangenen Fehler, erwünscht wäre hier wahrscheinlich "einunddreißig komma vierundzwanzig"
