### ISSUE TITLE
keine pdf-formulare

### ISSUE THREAD

**Issue by vv01f** [UweZiegenhagen/spendenquittungen-mit-latex#3]
leider lassen sich die PDF Dateien so noch nicht "hübsch" als Formular zur direkten Eingabe/Korrektur nutzen.
ginge wohl mit hyperref: http://ctan.space-pro.be/tex-archive/macros/latex/contrib/hyperref/doc/manual.html#x1-200006

**Comment by UweZiegenhagen** [comment]
Ja, das geht. Aber mein Fokus liegt ja darauf, die Dokumente automatisiert zu erstellen. Wenn ich sie manuell ausfüllen wollte, würde ich vermutlich die Word-Vorlage entsprechend erweitern. Da ist mir der Aufwand in LaTeX zu hoch.
