### ISSUE TITLE
"Sammelbestaetigung_Geldzuwendung.tex" is missing in repo

### ISSUE THREAD

**Issue by ventilator** [UweZiegenhagen/spendenquittungen-mit-latex#4]
Hi,

I happen to notice that the .tex file with the suitable variables to fill is missing in the repo.
The .py file references "Sammelbestaetigung_Geldzuwendung.tex" which is missing.
Can you please add the file?

BR

**Comment by UweZiegenhagen** [comment]
Added file "Sammelbestaetigung_Geldzuwendung_Py_Template.tex"
